### ISSUE TITLE
 Version 3 Milestone

### ISSUE THREAD

**Issue by quakerpunk** [quakerpunk/content-audit#1]
* [x] Update URL regular expression to account for new TLDs. 
* [ ] Import new library that supports newer versions of Microsoft Excel  
* [ ] Allow a user to choose between CSV or XLS file
* [ ] Refactor
* [ ] Bump up version number to 3.0
